Priorities should be optional
cloudposse/terraform-aws-alb-ingress pull request #26
Opened 2020-06-10 19:57 UTC by nitrocode

@aknysh @osterman please review if time permits

https://www.terraform.io/docs/providers/aws/r/lb_listener_rule.html

> `priority` - (Optional) The priority for the rule between `1` and `50000`. Leaving it unset will automatically set the rule with next available priority after currently existing highest rule. A listener can't have multiple rules with the same priority.

2020-06-16 22:13 UTC, osterman commented
/rebuild-readme

2020-06-17 13:24 UTC, nitrocode commented
/test all

2020-06-17 14:52 UTC, nitrocode commented
Ah same s3 bucket naming issue as mentioned in https://github.com/cloudposse/terraform-aws-alb-ingress/pull/27#issuecomment-645338064

2020-06-22 14:50 UTC, Gowiem requested changes

2020-06-22 14:50 UTC, Gowiem commented on main.tf
> +  priority     = var.unauthenticated_priority > 0 ? var.unauthenticated_priority + count.index : null
@nitrocode Previously this module never passed `null` as a value to these resources. Have you tested out what passing `null` does? I'm wondering if it was cause inconsistent applies or possibly errors?

2020-06-22 19:36 UTC, nitrocode commented
@Gowiem 

> Leaving it unset will automatically set the rule with next available priority after currently existing highest rule.

By setting it to `null`, the rule priority gets set automatically by amazon instead of us.

2020-06-22 21:59 UTC, nitrocode commented
/rebuild-readme

2020-06-22 23:57 UTC, Gowiem approved these changes
Aha @nitrocode, that sounds good 👍 :shipit:

2020-06-22 23:57 UTC, Gowiem commented
/test all

2020-06-23 00:07 UTC, merged

2020-06-23 00:10 UTC, Gowiem commented
@nitrocode Shipped as [0.11.0](https://github.com/cloudposse/terraform-aws-alb-ingress/releases/tag/0.11.0) 😎